# Save as .codeclimate.yml (note leading .) in project root directory
languages:
  Ruby: false
  JavaScript: true
  PHP: true
  Python: false
exclude_paths:
 - "assets/js/lib"
 - "assets/js/libs.js"
 - "assets/js/libs.min.js"
 - "assets/js/forms.js"
 - "assets/js/forms.min.js"
 - "assets/lib"
 - "assets/js/lib/colorpicker.js"