# Save as .codeclimate.yml (note leading .) in project root directory
languages:
  Ruby: false
  JavaScript: true
  PHP: true
  Python: false
exclude_paths:
 - "assets/js/colorpicker.min.js"
 - "assets/js/eye.js"
 - "assets/js/layout.js"
 - "assets/js/utils.js"
 - "assets/lib"
